name: Docker Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true

permissions:
  # Required to stop running workflows
  actions: write
  packages: write

jobs:
  build-docker-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      -
        name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Install Cosign
        uses: sigstore/cosign-installer@v2.0.1
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            elastic/harp
            ghcr.io/elastic/harp
      -
        id: build-and-push
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=${{ github.event.inputs.release }}
          tags: |
            ghcr.io/${{ github.repository }}/harp:latest
            ghcr.io/${{ github.repository }}/harp:v${{ github.event.inputs.release }}
          labels: ${{ steps.meta.outputs.labels }}
