name: Build GitHub release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    steps:
      -
        name: Extract artifacts from the docker image
        id: extract-std
        uses: shrink/actions-docker-extract@v1
        with:
          image: ghcr.io/elastic/harp/harp-artifacts:v${{ github.event.inputs.release }}
          path: '/app/.'
      -
        name: Extract FIPS artifacts from the docker image
        id: extract-fips
        uses: shrink/actions-docker-extract@v1
        with:
          image: ghcr.io/elastic/harp/harp-artifacts-fips:v${{ github.event.inputs.release }}
          path: '/app/.'
      -
        uses: sigstore/cosign-installer@v2.0.1
      -
        name: Assemble a package
        run: |
          mkdir .dist
          cp ${{ steps.extract-std.outputs.destination }}/* .dist/
          cp ${{ steps.extract-fips.outputs.destination }}/* .dist/
      -
        name: Create checksum
        id: create-checksum
        run: |
          cd .dist
          sha256sum * > checksum.txt
      -
        name: Generate provenance for Release
        uses: philips-labs/slsa-provenance-action@v0.7.2
        with:
          command: generate
          subcommand: files
          arguments: --artifact-path .dist --output-path '.dist/provenance.json'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      -
        name: Sign
        shell: bash
        run: |
          #!/bin/bash
          shopt -s expand_aliases
          cd .dist
          FILES="*"
          for f in $FILES;
          do
            case $f in
            *.sbom.json)
                gzip "$f"
                ;;
            checksum.txt|provenance.json)
                cosign sign-blob --key <(echo -n "${COSIGN_KEY}") "$f" > "$f.sig"
                ;;
            harp-*)
                sha256sum "$f" | cut -d " " -f 1 > "$f.sha256"
                cosign sign-blob --key <(echo -n "${COSIGN_KEY}") "$f" > "$f.sig"
                ;;
            esac
          done
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      -
        name: Verify
        shell: bash
        run: |
          #!/bin/bash
          shopt -s expand_aliases
          curl -sLO https://raw.githubusercontent.com/elastic/harp/cmd/harp/v{{ github.events.inputs.release }}/build/artifact/cosign.pub
          cd .dist
          FILES="*"
          for f in $FILES;
          do
            if [[ -f "$f.sig" ]];
            then
              cosign verify-blob --key ../cosign.pub --signature "$f.sig" $f
            fi
          done
      -
        name: Upload to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: '.dist/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: cmd/harp/v${{ github.event.inputs.release }}
