name: Create and pack release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          # normal
          - golang-image: "golang"
            golang-version: "1.17"
            tools-image: ghcr.io/elastic/harp/harp-tools:latest
            harp-image: harp-artifacts
            fips-mode: 0
          # fips
          - golang-image: "goboring/golang"
            golang-version: "1.16.7b7"
            tools-image: ghcr.io/elastic/harp/harp-tools-fips:latest
            harp-image: harp-artifacts-fips
            fips-mode: 1
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx
      -
        name: Set Dockerfile settings
        run: |
          echo Building $DOCKER_IMAGE_NAME with $GOLANG_IMAGE:$GOLANG_VERSION
          echo "DOCKERFILE_ONLY=1" >> $GITHUB_ENV
          echo "GOLANG_IMAGE=$GOLANG_IMAGE" >> $GITHUB_ENV
          echo "GOLANG_VERSION=$GOLANG_VERSION" >> $GITHUB_ENV
          echo "TOOL_IMAGE_NAME=$TOOL_IMAGE_NAME" >> $GITHUB_ENV
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "HARP_BUILD_FIPS_MODE=$FIPS_MODE" >> $GITHUB_ENV
        env:
          DOCKERFILE_ONLY: 1
          GOLANG_IMAGE: ${{ matrix.golang-image }}
          GOLANG_VERSION: ${{ matrix.golang-version }}
          TOOL_IMAGE_NAME: ${{ matrix.tools-image }}
          RELEASE: ${{ github.event.inputs.release }}
          FIPS_MODE: ${{ matrix.fips-mode }}
      -
        name: Generate Dockerfile
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: releaser:harp
      -
        name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.release
          pull: false
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/elastic/harp/${{ matrix.harp-image }}:v${{ github.event.inputs.release }}
            ghcr.io/elastic/harp/${{ matrix.harp-image }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          build-args: |
            GOLANG_IMAGE=${{ matrix.golang-image }}
            GOLANG_VERSION=${{ matrix.golang-version }}
            RELEASE=${{ github.event.inputs.release }}
      -
        name: Create SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/elastic/harp/${{ matrix.harp-image }}:v${{ github.event.inputs.release }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ github.token }}
          artifact-name: sbom.spdx
          format: spdx
      -
        uses: sigstore/cosign-installer@main
      -
        name: Sign image and add attestations
        run: |
          echo -n "${COSIGN_PASSWORD}" | \
          cosign sign --key <(echo -n "${COSIGN_KEY}") \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            -a "ref=${{ github.sha }}" \
            ghcr.io/elastic/harp/${{ matrix.harp-image }}:v${{ github.event.inputs.release }}
          cosign attach sbom --sbom sbom.spdx ghcr.io/elastic/harp/${{ matrix.harp-image }}:v${{ github.event.inputs.release }}
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      -
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      -
        name: Prepare distribution
        run: |
          mkdir .dist
      -
        name: Extract artifacts from the docker image
        uses: shrink/actions-docker-extract@v1
        with:
          image: ghcr.io/elastic/harp/${{ matrix.harp-image }}:v${{ github.event.inputs.release }}
          path: '/app/.'
      -
        name: Create archives
        id: create-archives
        run: |
          cd ${{ steps.extract.outputs.destination }}
          find . -maxdepth 1 -mindepth 1 -type f -exec tar czvf --remove-files {}.tar.gz {} \;
      -
        name: Create checksum
        id: create-checksum
        run: |
          cd ${{ steps.extract.outputs.destination }}
          sha512sum *.tar.gz > harp-checksum.txt
      -
        name: Sign the checksum
        run: |
          cd ${{ steps.extract.outputs.destination }}
          echo -n "${COSIGN_PASSWORD}" | \
            cosign sign-blob --key <(echo -n "${COSIGN_KEY}") \
              --output=harp-checksum.txt.sig \
              harp-checksum.txt
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      -
        name: Upload Dist
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.extract.outputs.destination }}
          name: harp-v${{ github.event.inputs.release }}

