name: Create and pack release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          # normal
          - golang-image: "golang"
            golang-version: "1.17"
            tools-image: harp-tools
            harp-image: harp-artifacts
          # fips
          - golang-image: "goboring/golang"
            golang-version: "1.16.7b7"
            tools-image: harp-tools-fips
            harp-image: harp-artifacts-fips
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      -
        name: Set Dockerfile settings
        run: |
          echo Building $DOCKER_IMAGE_NAME with $GOLANG_IMAGE:$GOLANG_VERSION
          echo "DOCKERFILE_ONLY=1" >> $GITHUB_ENV
          echo "GOLANG_IMAGE=$GOLANG_IMAGE" >> $GITHUB_ENV
          echo "GOLANG_VERSION=$GOLANG_VERSION" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME" >> $GITHUB_ENV
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
        env:
          DOCKERFILE_ONLY: 1
          GOLANG_IMAGE: ${{ matrix.golang-image }}
          GOLANG_VERSION: ${{ matrix.golang-version }}
          DOCKER_IMAGE_NAME: ${{ matrix.tools-image }}
          RELEASE: ${{ github.event.inputs.release }}
      -
        name: Generate Dockerfile
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: releaser:harp
      -
        name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.release
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/elastic/harp/${{ matrix.harp-image }}:v${{ github.event.inputs.release }}
            ghcr.io/elastic/harp/${{ matrix.harp-image }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            GOLANG_IMAGE=${{ matrix.golang-image }}
            GOLANG_VERSION=${{ matrix.golang-version }}
